# Generated by Django 2.2 on 2021-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210318_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
